CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_title TEXT NOT NULL,
    picture TEXT NOT NULL,
    region TEXT NOT NULL,
    instructions TEXT NOT NULL,
    video TEXT NOT NULL,
    ingredients TEXT NOT NULL
);