CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_title TEXT NOT NULL,
    region TEXT NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    instructions TEXT NOT NULL,
    ingredients TEXT NOT NULL
);